config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root "events#index"

  resources :events do
    resources :comments, only: %i[create destroy]

    resources :subscriptions, only: %i[create destroy]
    resources :photos, only: %i[create destroy]

    post :show, on: :member
  end
  
  resources :users, only: %i[show edit update]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event
  belongs_to :user, optional: true

  validates :event, presence: true
  validates :body, presence: true
  # Это поле должно быть, только если не выполняется user.present?
  # (у объекта не задан юзер)
  validates :user_name, presence: true, unless: -> { user.present? } 
  # В качестве юзернейма, если у нас прописан юзер, мы должны брать не поле из базы, 
  # а имя этого юзера. Переопределим для этого user_name ниже:
  def user_name
    if user.present?
     user.name
    else
     super
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
   # Задаем родительский event для подписки
  before_action :set_event, only: %i[create destroy]

 # Задаем подписку, которую юзер хочет удалить
  before_action :set_comment, only: :destroy
 
  def create
    # Создаём объект @new_comment из @event
    @new_comment = @event.comments.build(comment_params)
    # Проставляем пользователя, если он задан
    @new_comment.user = current_user
       
    if @new_comment.save
       # уведомляем всех подписчиков о новом комментарии
      NotifySubscribersJob.perform_later(@new_comment)
      # Если сохранился, редирект на страницу самого события
      redirect_to @event, notice: I18n.t('controllers.comments.created')
    else
      # Если ошибки — рендерим здесь же шаблон события (своих шаблонов у коммента нет)
      render 'events/show', alert: I18n.t('controllers.comments.error')
    end
  end
  
  def destroy
    message = { notice: I18n.t("controllers.comments.destroyed") }

    if current_user_can_edit?(@comment)
      @comment.destroy!
    else
      message = { alert: I18n.t('controllers.comments.error') }
    end
  
    redirect_to @event, message
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end
  
  # Комментарий будем искать не по всей базе,
  # а у конкретного события
  def set_comment
    @comment = @event.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body, :user_name)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="buffer-both">
  <p><%= comment.body %></p>
  <p>
    <span>
      <% if comment.user.present? %>
        <%= render partial: 'users/user', object: comment.user %>
      <% else %>
        <em><strong><%= comment.user_name %></strong></em>
      <% end %>
    </span>
    <em><%= l comment.created_at, format: :short %></em>
    <% if current_user_can_edit?(comment) %>
      <%= button_to I18n.t('button.delete'), event_comment_path(comment.event, comment), method: :delete,
      form: { data: { turbo_confirm: I18n.t('comments.comment.destroy_confirm') }},
      class: 'btn btn-primary' %>
    <% end %>  
  </p>
</div>

app/views/comments/_form.html.erb
<%= form_for([@event, comment], data: { turbo: false }) do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: comment} %>
  
  <div class="buffer-bottom-forms">
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, class: 'form-control' %>
    </div>

    <% unless user_signed_in? %>
        <div class="form-group">
          <%= f.label :user_name %>
          <%= f.text_field :user_name, class: 'form-control' %>
        </div>
    <% end %>
 </div>
  <div class="actions">
    <%= f.submit I18n.t('button.send'), class: 'btn btn-primary' %>
  </div>
<% end %>