config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root "events#index"

  resources :events do
    resources :comments, only: %i[create destroy]

    resources :subscriptions, only: %i[create destroy]
    resources :photos, only: %i[create destroy]

    post :show, on: :member
  end
  
  resources :users, only: %i[show edit update]
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :event
  belongs_to :user, optional: true
  
   # Проверки user_name и user_email выполняются,
   # только если user не задан
   # То есть для анонимных пользователей
  validates :user_name, presence: true, unless: -> { user.present? } 
 
  validates :user_email, presence: true, format: /\A[a-zA-Z0-9\-_.]+@[a-zA-Z0-9\-_.]+\z/, unless: -> { user.present? }
  # Для конкретного event_id один юзер может подписаться только один раз (если юзер задан)
  validates :user, uniqueness: { scope: :event_id }, if: -> { user.present? }

  # Или один email может использоваться только один раз (если анонимная подписка)
  validates :user_email, uniqueness: { scope: :event_id }, unless: -> { user.present? }
  
  validate :check_email_if_exist,  unless: -> { user.present? }

  validate :subscription_permitted, if: -> { user.present? }
  # Если есть юзер, выдаем его имя,
  # если нет – дергаем исходный метод
  def user_name
    if user.present?
     user.name
    else
     super
    end
  end

  # Если есть юзер, выдаем его email,
  # если нет – дергаем исходный метод
  def user_email
    if user.present?
      user.email
    else
      super
    end
  end

  def check_email_if_exist
    errors.add(:user_email, :taken)  if User.where(email: user_email).exists?
  end

  def subscription_permitted
    errors.add(:base, :event_user_error) if user == event.user
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  # Задаем родительский event для подписки
  before_action :set_event, only: %i[create destroy]
  
  # Задаем подписку, которую юзер хочет удалить
  before_action :set_subscription, only: :destroy

  def create
    # Болванка для новой подписки
    @new_subscription = @event.subscriptions.build(subscription_params)
    @new_subscription.user = current_user

    if @new_subscription.save
       # Если сохранилось, отправляем письмо
      # Пишем название класса, потом метода и передаём параметры
      # И доставляем методом .deliver_now (то есть в этом же потоке)
      NotifySubscribersJob.perform_later(@new_subscription)
      # Если сохранилась, редиректим на страницу самого события
      redirect_to @event, notice: I18n.t('controllers.subscriptions.created')
    else 
      render 'events/show', alert: I18n.t('controllers.subscriptions.error')  
    end
  end
  
  def destroy
    message = {notice: I18n.t('controllers.subscriptions.destroyed')}
    if current_user_can_edit?(@subscription)
      @subscription.destroy
    else
      message = {alert: I18n.t('controllers.subscriptions.error')}
    end
  
    redirect_to @event, message
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_subscription
    @subscription = @event.subscriptions.find(params[:id])
  end
    
  def set_event
    @event = Event.find(params[:event_id])
  end
  
  def subscription_params
    # .fetch разрешает в params отсутствие ключа :subscription
    params.fetch(:subscription, {}).permit(:user_email, :user_name)
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_for([@event, subscription], data: { turbo: false }) do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: subscription} %>
  
  <div class="buffer-bottom-forms">
    <% unless user_signed_in? %>
      <div class="form-group">
        <%= f.label :user_name %>
        <%= f.text_field :user_name, class: 'form-control' %>
      </div>
    
      <div class="form-group">
        <%= f.label :user_email %>
        <%= f.text_field :user_email, class: 'form-control' %>
      </div>
    <% end %>
  </div>
 
  <div class="actions">
    <%= f.submit I18n.t('button.subscribe'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/subscriptions/_subscription.html.erb
<span class="subscription">
  <% if subscription.user.present? %>
    <%= render partial: 'users/user', object: subscription.user %>
  <% else %>
    <em><%= subscription.user_name %></em>
  <% end %>
  <% if current_user_can_edit?(subscription) %>
    <%= button_to I18n.t('button.delete'), event_subscription_path(subscription.event, subscription), 
      method: :delete, form: { data: { turbo_confirm: I18n.t('subscriptions.subscription.destroy_confirm') }},
      class: 'btn btn-primary' %>
  <% end %>
</span>